# @generated by tools/gen_text_dsl.py from tools/_dsl_grammar.py — DO NOT EDIT.
# Regenerate with: python tools/gen_text_dsl.py
# ruff: noqa
# Generated by LangForge — standalone lexer
from __future__ import annotations
import re
from dataclasses import dataclass, field
from typing import Iterator

_RE_root_r0 = re.compile('[ \\t\\r\\n]+')
_RE_root_r1 = re.compile('//[^\\n]*')
_RE_root_r2 = re.compile('/\\*[\\s\\S]*?\\*/')
_RE_root_r3 = re.compile('"(?:[^"\\\\]|\\\\.)*"')
_RE_root_r4 = re.compile("'(?:[^'\\\\]|\\\\.)*'")
_RE_root_r5 = re.compile('[0-9]+(?:\\.[0-9]+)?')
_RE_root_r6 = re.compile('(?:provider|message|foreach|dialog|window|button|escape|chunk|slice|false|menu|defs|else|node|true|null|row|ref|and|not|in|if|or|t)(?!\\w)')
_RE_root_r7 = re.compile('[A-Za-z_](?:[A-Za-z_]|[0-9])*')
_RE_root_r8 = re.compile('<=|>=|==|!=')
_RE_root_r9 = re.compile('[{}()\\[\\].,:;=<>+\\-*/%]')

_DYN_TEMPLATES = {}
_STATE_FUNCS = {'root': '_lex_root'}
_EOF_CONFIGS = {'root': {'emit': ['EOF'], 'error': None}}

_INTERP_RE = re.compile(r'\$\{meta\.([A-Za-z_][A-Za-z0-9_]*)(?:\|([a-z]+))?\}')


def _build_dyn_regex(template, meta):
    def _r(m):
        k = m.group(1); mod = m.group(2)
        v = str(meta.get(k, ''))
        return v if mod == 'raw' else re.escape(v)
    return re.compile(_INTERP_RE.sub(_r, template))


def _build_dyn_delimiter(template, meta):
    return _build_dyn_regex(template, meta)


def _kw_match(regex, text, pos):
    m = regex.match(text, pos)
    if m is None:
        return None
    if pos > 0 and re.match(r'\w', text[pos - 1]):
        return None
    return m


def _until_match(delim_re, text, pos):
    m = delim_re.search(text, pos)
    end = m.start() if m else len(text)
    if end == pos:
        return None
    return re.compile(re.escape(text[pos:end])).match(text, pos)


def _tmpl_resolve(config, m):
    template = config['template']
    captures = config.get('captures', {})
    result = template
    for placeholder, group_name in captures.items():
        result = result.replace(f'${{{placeholder}}}', m.group(group_name))
    return result


def _pos(text, pos):
    lines_before = text[:pos].split('\n')
    return _Position(len(lines_before), len(lines_before[-1]) + 1, pos)


@dataclass
class _Position:
    line: int
    col: int
    offset: int


@dataclass
class _Token:
    type: str
    value: str
    position: _Position


@dataclass
class _Frame:
    state: str
    meta: dict
    _dyn: list = field(default_factory=list)
    _buf: str = ''
    _compiled_state: str = ''

def _compile_frame_dyn(state_name, meta):
    _r = []
    for kind, tmpl in _DYN_TEMPLATES.get(state_name, []):
        if kind == 'dyn_pattern':
            _r.append(_build_dyn_regex(tmpl, meta))
        else:
            _r.append(_build_dyn_delimiter(tmpl, meta))
    return _r

def _lex_root(text, pos, stack, frame):
    m = _RE_root_r0.match(text, pos)
    if m is not None:
        return [], m.end()
    m = _RE_root_r1.match(text, pos)
    if m is not None:
        return [], m.end()
    m = _RE_root_r2.match(text, pos)
    if m is not None:
        return [], m.end()
    m = _RE_root_r3.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('STRING', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r4.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('STRING', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r5.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('NUMBER', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _kw_match(_RE_root_r6, text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('KW', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r7.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('IDENT', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r8.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('SYM', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    m = _RE_root_r9.match(text, pos)
    if m is not None:
        _result = []
        _toks = [_Token('SYM', m.group(), _pos(text, pos))]
        _result.extend(_toks)
        return _result, m.end()
    return None

class Lexer:
    def tokenize(self, text: str) -> Iterator[_Token]:
        frame = _Frame('root', {})
        frame._dyn = _compile_frame_dyn('root', {})
        stack = [frame]
        pos = 0
        while pos < len(text):
            frame = stack[-1]
            # re-compile dyn rules if state changed via set_state
            if frame._compiled_state != frame.state:
                frame._dyn = _compile_frame_dyn(frame.state, frame.meta)
                frame._compiled_state = frame.state
            _fn_name = _STATE_FUNCS.get(frame.state)
            if _fn_name is None:
                raise ValueError(f"Unknown state {frame.state!r}")
            _fn = globals()[_fn_name]
            result = _fn(text, pos, stack, frame)
            if result is None and False:
                result = _lex___global__(text, pos, stack, frame)
            if result is None:
                _lines = text[:pos].split('\n')
                _loc = f'{len(_lines)}:{len(_lines[-1]) + 1}'
                raise ValueError(
                    f"No rule matched in state {frame.state!r} at {_loc}: "
                    f"{text[pos:pos+20]!r}"
                )
            tokens, new_pos = result
            # update top frame after possible push/set_state
            top = stack[-1]
            if top._compiled_state != top.state:
                top._dyn = _compile_frame_dyn(top.state, top.meta)
                top._compiled_state = top.state
            yield from tokens
            pos = new_pos

        frame = stack[-1]
        eof_cfg = _EOF_CONFIGS.get(frame.state)
        if eof_cfg:
            if eof_cfg.get('error'):
                raise SyntaxError(eof_cfg['error'])
            lines_before = text.split('\n')
            _p = _Position(len(lines_before), len(lines_before[-1]) + 1, len(text))
            for token_type in eof_cfg.get('emit', []):
                yield _Token(token_type, '', _p)

