# @generated by tools/gen_text_dsl.py from tools/_dsl_grammar.py — DO NOT EDIT.
# Regenerate with: python tools/gen_text_dsl.py
# ruff: noqa
# Generated by LangForge — Earley parser
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any


@dataclass
class Position:
    line: int
    col: int
    offset: int


@dataclass
class TerminalNode:
    terminal_name: str
    token_type: str
    token_value: str
    position: Position | None = None


@dataclass
class NonTerminalNode:
    name: str
    children: list[Any] = field(default_factory=list)


_RULES = [
    ('file', [('n', 'dialog'), ('t', 'EOF', 'EOF', None)]),
    ('dialog', [('t', 'DIALOG', 'KW', 'dialog'), ('n', '_opt_0'), ('n', '_opt_1'), ('t', 'LBRACE', 'SYM', '{'), ('n', '_rep_2'), ('t', 'RBRACE', 'SYM', '}')]),
    ('_opt_0', [('t', 'IDENT', 'IDENT', None)]),
    ('_opt_0', []),
    ('_opt_1', [('n', 'map')]),
    ('_opt_1', []),
    ('_rep_2', []),
    ('_rep_2', [('n', 'dialog_member'), ('n', '_rep_2')]),
    ('dialog_member', [('n', 'defs_block')]),
    ('dialog_member', [('n', 'window')]),
    ('map', [('t', 'LPAREN', 'SYM', '('), ('n', 'pair_list'), ('t', 'RPAREN', 'SYM', ')')]),
    ('pair_list', [('n', 'pair')]),
    ('pair_list', [('n', 'pair'), ('t', 'COMMA', 'SYM', ','), ('n', 'pair_list')]),
    ('pair', [('t', 'IDENT', 'IDENT', None), ('t', 'EQ', 'SYM', '='), ('n', 'expr')]),
    ('defs_block', [('t', 'DEFS', 'KW', 'defs'), ('t', 'LBRACE', 'SYM', '{'), ('n', '_rep_3'), ('t', 'RBRACE', 'SYM', '}')]),
    ('_rep_3', []),
    ('_rep_3', [('n', 'def_entry'), ('n', '_rep_3')]),
    ('def_entry', [('t', 'IDENT', 'IDENT', None), ('t', 'COLON', 'SYM', ':'), ('n', 'value')]),
    ('window', [('t', 'WINDOW', 'KW', 'window'), ('n', '_opt_4'), ('n', '_opt_5'), ('t', 'LBRACE', 'SYM', '{'), ('n', '_rep_6'), ('t', 'RBRACE', 'SYM', '}')]),
    ('_opt_4', [('t', 'IDENT', 'IDENT', None)]),
    ('_opt_4', []),
    ('_opt_5', [('n', 'map')]),
    ('_opt_5', []),
    ('_rep_6', []),
    ('_rep_6', [('n', 'window_member'), ('n', '_rep_6')]),
    ('window_member', [('n', 'field')]),
    ('window_member', [('n', 'media_group')]),
    ('window_member', [('n', 'menu_decl')]),
    ('window_member', [('n', 'menu_ref')]),
    ('window_member', [('n', 'message_decl')]),
    ('window_member', [('n', 'message_ref')]),
    ('message_decl', [('t', 'MESSAGE', 'KW', 'message'), ('n', '_opt_7'), ('n', '_opt_8'), ('t', 'LBRACE', 'SYM', '{'), ('n', '_rep_9'), ('t', 'RBRACE', 'SYM', '}')]),
    ('_opt_7', [('t', 'IDENT', 'IDENT', None)]),
    ('_opt_7', []),
    ('_opt_8', [('n', 'map')]),
    ('_opt_8', []),
    ('_rep_9', []),
    ('_rep_9', [('n', 'content_member'), ('n', '_rep_9')]),
    ('message_ref', [('t', 'MESSAGE', 'KW', 'message'), ('t', 'LPAREN', 'SYM', '('), ('n', 'expr'), ('t', 'RPAREN', 'SYM', ')')]),
    ('content_member', [('n', 'field')]),
    ('content_member', [('n', 'media_group')]),
    ('field', [('t', 'IDENT', 'IDENT', None), ('t', 'COLON', 'SYM', ':'), ('n', 'expr')]),
    ('menu_decl', [('t', 'MENU', 'KW', 'menu'), ('n', '_opt_10'), ('n', '_opt_11'), ('t', 'LBRACE', 'SYM', '{'), ('n', '_rep_12'), ('t', 'RBRACE', 'SYM', '}')]),
    ('_opt_10', [('t', 'IDENT', 'IDENT', None)]),
    ('_opt_10', []),
    ('_opt_11', [('n', 'map')]),
    ('_opt_11', []),
    ('_rep_12', []),
    ('_rep_12', [('n', 'value'), ('n', '_rep_12')]),
    ('menu_ref', [('t', 'MENU', 'KW', 'menu'), ('t', 'LPAREN', 'SYM', '('), ('n', 'expr'), ('t', 'RPAREN', 'SYM', ')')]),
    ('row', [('t', 'ROW', 'KW', 'row'), ('t', 'LBRACK', 'SYM', '['), ('t', 'RBRACK', 'SYM', ']')]),
    ('row', [('t', 'ROW', 'KW', 'row'), ('t', 'LBRACK', 'SYM', '['), ('n', 'value_list'), ('t', 'RBRACK', 'SYM', ']')]),
    ('value_list', [('n', 'value')]),
    ('value_list', [('n', 'value'), ('t', 'COMMA', 'SYM', ','), ('n', 'value_list')]),
    ('if_stmt', [('t', 'IF', 'KW', 'if'), ('n', 'expr'), ('n', 'block')]),
    ('if_stmt', [('t', 'IF', 'KW', 'if'), ('n', 'expr'), ('n', 'block'), ('t', 'ELSE', 'KW', 'else'), ('n', 'block')]),
    ('foreach_stmt', [('t', 'FOREACH', 'KW', 'foreach'), ('t', 'IDENT', 'IDENT', None), ('t', 'IN', 'KW', 'in'), ('n', 'expr'), ('n', 'block')]),
    ('foreach_stmt', [('t', 'FOREACH', 'KW', 'foreach'), ('t', 'IDENT', 'IDENT', None), ('t', 'COMMA', 'SYM', ','), ('t', 'IDENT', 'IDENT', None), ('t', 'IN', 'KW', 'in'), ('n', 'expr'), ('n', 'block')]),
    ('chunk_stmt', [('t', 'CHUNK', 'KW', 'chunk'), ('n', 'expr'), ('n', 'block')]),
    ('block', [('t', 'LBRACE', 'SYM', '{'), ('n', '_rep_13'), ('t', 'RBRACE', 'SYM', '}')]),
    ('_rep_13', []),
    ('_rep_13', [('n', 'value'), ('n', '_rep_13')]),
    ('button_decl', [('t', 'BUTTON', 'KW', 'button'), ('t', 'IDENT', 'IDENT', None), ('n', 'map')]),
    ('button_decl', [('t', 'BUTTON', 'KW', 'button'), ('n', 'map')]),
    ('media_group', [('t', 'IDENT', 'IDENT', None), ('t', 'LBRACE', 'SYM', '{'), ('n', '_rep_14'), ('t', 'RBRACE', 'SYM', '}')]),
    ('_rep_14', []),
    ('_rep_14', [('n', 'media_member'), ('n', '_rep_14')]),
    ('media_member', [('n', 'media_item')]),
    ('media_member', [('n', 'media_foreach')]),
    ('media_member', [('n', 'media_if')]),
    ('media_foreach', [('t', 'FOREACH', 'KW', 'foreach'), ('t', 'IDENT', 'IDENT', None), ('t', 'IN', 'KW', 'in'), ('n', 'expr'), ('n', 'media_block')]),
    ('media_foreach', [('t', 'FOREACH', 'KW', 'foreach'), ('t', 'IDENT', 'IDENT', None), ('t', 'COMMA', 'SYM', ','), ('t', 'IDENT', 'IDENT', None), ('t', 'IN', 'KW', 'in'), ('n', 'expr'), ('n', 'media_block')]),
    ('media_if', [('t', 'IF', 'KW', 'if'), ('n', 'expr'), ('n', 'media_block')]),
    ('media_if', [('t', 'IF', 'KW', 'if'), ('n', 'expr'), ('n', 'media_block'), ('t', 'ELSE', 'KW', 'else'), ('n', 'media_block')]),
    ('media_block', [('t', 'LBRACE', 'SYM', '{'), ('n', '_rep_15'), ('t', 'RBRACE', 'SYM', '}')]),
    ('_rep_15', []),
    ('_rep_15', [('n', 'media_member'), ('n', '_rep_15')]),
    ('media_item', [('t', 'IDENT', 'IDENT', None), ('n', 'expr'), ('n', '_rep_16')]),
    ('_rep_16', []),
    ('_rep_16', [('n', 'media_satellite'), ('n', '_rep_16')]),
    ('media_satellite', [('t', 'IDENT', 'IDENT', None), ('t', 'COLON', 'SYM', ':'), ('n', 'expr')]),
    ('value', [('n', 'expr')]),
    ('value', [('n', 'button_decl')]),
    ('value', [('n', 'row')]),
    ('value', [('n', 'if_stmt')]),
    ('value', [('n', 'foreach_stmt')]),
    ('value', [('n', 'chunk_stmt')]),
    ('expr', [('n', 'or_expr')]),
    ('or_expr', [('n', 'or_expr'), ('t', 'OR', 'KW', 'or'), ('n', 'and_expr')]),
    ('or_expr', [('n', 'and_expr')]),
    ('and_expr', [('n', 'and_expr'), ('t', 'AND', 'KW', 'and'), ('n', 'not_expr')]),
    ('and_expr', [('n', 'not_expr')]),
    ('not_expr', [('t', 'NOT', 'KW', 'not'), ('n', 'not_expr')]),
    ('not_expr', [('n', 'cmp_expr')]),
    ('cmp_expr', [('n', 'cmp_expr'), ('t', 'LT', 'SYM', '<'), ('n', 'add_expr')]),
    ('cmp_expr', [('n', 'cmp_expr'), ('t', 'GT', 'SYM', '>'), ('n', 'add_expr')]),
    ('cmp_expr', [('n', 'cmp_expr'), ('t', 'LE', 'SYM', '<='), ('n', 'add_expr')]),
    ('cmp_expr', [('n', 'cmp_expr'), ('t', 'GE', 'SYM', '>='), ('n', 'add_expr')]),
    ('cmp_expr', [('n', 'cmp_expr'), ('t', 'EQEQ', 'SYM', '=='), ('n', 'add_expr')]),
    ('cmp_expr', [('n', 'cmp_expr'), ('t', 'NE', 'SYM', '!='), ('n', 'add_expr')]),
    ('cmp_expr', [('n', 'cmp_expr'), ('t', 'IN', 'KW', 'in'), ('n', 'add_expr')]),
    ('cmp_expr', [('n', 'cmp_expr'), ('t', 'NOT', 'KW', 'not'), ('t', 'IN', 'KW', 'in'), ('n', 'add_expr')]),
    ('cmp_expr', [('n', 'add_expr')]),
    ('add_expr', [('n', 'add_expr'), ('t', 'PLUS', 'SYM', '+'), ('n', 'mul_expr')]),
    ('add_expr', [('n', 'add_expr'), ('t', 'MINUS', 'SYM', '-'), ('n', 'mul_expr')]),
    ('add_expr', [('n', 'mul_expr')]),
    ('mul_expr', [('n', 'mul_expr'), ('t', 'STAR', 'SYM', '*'), ('n', 'unary')]),
    ('mul_expr', [('n', 'mul_expr'), ('t', 'SLASH', 'SYM', '/'), ('n', 'unary')]),
    ('mul_expr', [('n', 'mul_expr'), ('t', 'PERCENT', 'SYM', '%'), ('n', 'unary')]),
    ('mul_expr', [('n', 'unary')]),
    ('unary', [('t', 'MINUS', 'SYM', '-'), ('n', 'unary')]),
    ('unary', [('n', 'primary')]),
    ('primary', [('t', 'NUMBER', 'NUMBER', None)]),
    ('primary', [('t', 'STRING', 'STRING', None)]),
    ('primary', [('t', 'TRUE', 'KW', 'true')]),
    ('primary', [('t', 'FALSE', 'KW', 'false')]),
    ('primary', [('t', 'NULL', 'KW', 'null')]),
    ('primary', [('n', 'path')]),
    ('primary', [('n', 'call')]),
    ('primary', [('n', 't_call')]),
    ('primary', [('n', 'provider_call')]),
    ('primary', [('n', 'ref_call')]),
    ('primary', [('n', 'slice_call')]),
    ('primary', [('n', 'proto_call')]),
    ('primary', [('n', 'map')]),
    ('primary', [('t', 'LPAREN', 'SYM', '('), ('n', 'expr'), ('t', 'RPAREN', 'SYM', ')')]),
    ('primary', [('t', 'LBRACK', 'SYM', '['), ('t', 'RBRACK', 'SYM', ']')]),
    ('primary', [('t', 'LBRACK', 'SYM', '['), ('n', 'value_list'), ('t', 'RBRACK', 'SYM', ']')]),
    ('path', [('t', 'IDENT', 'IDENT', None)]),
    ('path', [('n', 'path'), ('t', 'DOT', 'SYM', '.'), ('t', 'IDENT', 'IDENT', None)]),
    ('path', [('n', 'path'), ('t', 'DOT', 'SYM', '.'), ('t', 'NUMBER', 'NUMBER', None)]),
    ('call', [('t', 'IDENT', 'IDENT', None), ('t', 'LPAREN', 'SYM', '('), ('t', 'RPAREN', 'SYM', ')')]),
    ('call', [('t', 'IDENT', 'IDENT', None), ('t', 'LPAREN', 'SYM', '('), ('n', 'arg_list'), ('t', 'RPAREN', 'SYM', ')')]),
    ('arg_list', [('n', 'expr')]),
    ('arg_list', [('n', 'expr'), ('t', 'COMMA', 'SYM', ','), ('n', 'arg_list')]),
    ('t_call', [('t', 'T', 'KW', 't'), ('t', 'LPAREN', 'SYM', '('), ('n', 'expr'), ('t', 'RPAREN', 'SYM', ')')]),
    ('provider_call', [('t', 'PROVIDER', 'KW', 'provider'), ('t', 'LPAREN', 'SYM', '('), ('n', 'expr'), ('t', 'RPAREN', 'SYM', ')')]),
    ('provider_call', [('t', 'PROVIDER', 'KW', 'provider'), ('t', 'LPAREN', 'SYM', '('), ('n', 'expr'), ('t', 'COMMA', 'SYM', ','), ('n', 'pair_list'), ('t', 'RPAREN', 'SYM', ')')]),
    ('ref_call', [('t', 'REF', 'KW', 'ref'), ('t', 'IDENT', 'IDENT', None)]),
    ('ref_call', [('t', 'REF', 'KW', 'ref'), ('t', 'LPAREN', 'SYM', '('), ('n', 'expr'), ('t', 'RPAREN', 'SYM', ')')]),
    ('slice_call', [('t', 'SLICE', 'KW', 'slice'), ('t', 'LPAREN', 'SYM', '('), ('n', 'arg_list'), ('t', 'RPAREN', 'SYM', ')')]),
    ('proto_call', [('t', 'BUTTON', 'KW', 'button'), ('t', 'LPAREN', 'SYM', '('), ('n', 'expr'), ('t', 'RPAREN', 'SYM', ')')]),
]

_NT_INDEX = {'file': [0], 'dialog': [1], '_opt_0': [2, 3], '_opt_1': [4, 5], '_rep_2': [6, 7], 'dialog_member': [8, 9], 'map': [10], 'pair_list': [11, 12], 'pair': [13], 'defs_block': [14], '_rep_3': [15, 16], 'def_entry': [17], 'window': [18], '_opt_4': [19, 20], '_opt_5': [21, 22], '_rep_6': [23, 24], 'window_member': [25, 26, 27, 28, 29, 30], 'message_decl': [31], '_opt_7': [32, 33], '_opt_8': [34, 35], '_rep_9': [36, 37], 'message_ref': [38], 'content_member': [39, 40], 'field': [41], 'menu_decl': [42], '_opt_10': [43, 44], '_opt_11': [45, 46], '_rep_12': [47, 48], 'menu_ref': [49], 'row': [50, 51], 'value_list': [52, 53], 'if_stmt': [54, 55], 'foreach_stmt': [56, 57], 'chunk_stmt': [58], 'block': [59], '_rep_13': [60, 61], 'button_decl': [62, 63], 'media_group': [64], '_rep_14': [65, 66], 'media_member': [67, 68, 69], 'media_foreach': [70, 71], 'media_if': [72, 73], 'media_block': [74], '_rep_15': [75, 76], 'media_item': [77], '_rep_16': [78, 79], 'media_satellite': [80], 'value': [81, 82, 83, 84, 85, 86], 'expr': [87], 'or_expr': [88, 89], 'and_expr': [90, 91], 'not_expr': [92, 93], 'cmp_expr': [94, 95, 96, 97, 98, 99, 100, 101, 102], 'add_expr': [103, 104, 105], 'mul_expr': [106, 107, 108, 109], 'unary': [110, 111], 'primary': [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127], 'path': [128, 129, 130], 'call': [131, 132], 'arg_list': [133, 134], 't_call': [135], 'provider_call': [136, 137], 'ref_call': [138, 139], 'slice_call': [140], 'proto_call': [141]}
_START = 'file'

def _matches(sym, token_type, token_value):
    _, name, tok_t, tok_v = sym
    if tok_t != '*' and token_type != tok_t:
        return False
    if tok_v is not None and token_value != tok_v:
        return False
    return True


def _parse_earley(tokens):
    n = len(tokens)
    chart = [[] for _ in range(n + 1)]
    in_chart = [set() for _ in range(n + 1)]

    def add(i, item):
        if item not in in_chart[i]:
            chart[i].append(item)
            in_chart[i].add(item)

    for ri in _NT_INDEX.get(_START, []):
        add(0, (ri, 0, 0))

    for i in range(n + 1):
        j = 0
        while j < len(chart[i]):
            rule_idx, dot, origin = chart[i][j]
            j += 1
            head, body = _RULES[rule_idx]
            if dot == len(body):
                for p_ri, p_dot, p_orig in chart[origin]:
                    _, p_body = _RULES[p_ri]
                    if p_dot < len(p_body) and p_body[p_dot][0] == 'n' and p_body[p_dot][1] == head:
                        add(i, (p_ri, p_dot + 1, p_orig))
            elif body[dot][0] == 'n':
                for ri in _NT_INDEX.get(body[dot][1], []):
                    add(i, (ri, 0, i))
            else:
                if i < n and _matches(body[dot], tokens[i].type, tokens[i].value):
                    add(i + 1, (rule_idx, dot + 1, origin))

    completed = {}
    for e, items in enumerate(chart):
        for rule_idx, dot, origin in items:
            head, body = _RULES[rule_idx]
            if dot == len(body):
                key = (head, origin, e)
                if key in completed:
                    completed[key].append(rule_idx)
                else:
                    completed[key] = [rule_idx]

    _memo = {}

    def _recover(ri, s, e):
        _result = None
        stack = [('R', ri, s, e)]

        while stack:
            tag = stack[-1][0]

            if tag == 'R':
                _, ri_, s_, e_ = stack.pop()
                key = ('r', ri_, s_, e_)
                if key in _memo:
                    _result = _memo[key]
                else:
                    head_, body_ = _RULES[ri_]
                    stack.append(('R_DONE', key, head_))
                    stack.append(('B', body_, 0, s_, e_))

            elif tag == 'R_DONE':
                _, key, head_ = stack.pop()
                _result = NonTerminalNode(head_, _result) if _result is not None else None
                _memo[key] = _result

            elif tag == 'B':
                _, body_, pos_, s_, e_ = stack.pop()
                bkey = (id(body_), pos_, s_, e_)
                if bkey in _memo:
                    _result = _memo[bkey]
                elif pos_ >= len(body_):
                    _result = [] if s_ == e_ else None
                    _memo[bkey] = _result
                else:
                    sym_ = body_[pos_]
                    if sym_[0] == 't':
                        if s_ >= e_ or not _matches(sym_, tokens[s_].type, tokens[s_].value):
                            _result = None
                            _memo[bkey] = None
                        else:
                            _p = tokens[s_].position
                            _tpos = Position(_p.line, _p.col, _p.offset) if _p is not None else None
                            tnode = TerminalNode(sym_[1], tokens[s_].type, tokens[s_].value, _tpos)
                            stack.append(('B_TERM_DONE', bkey, tnode))
                            stack.append(('B', body_, pos_ + 1, s_ + 1, e_))
                    else:
                        stack.append(('B_NT_LOOP', bkey, body_, pos_, s_, e_, sym_[1], s_))

            elif tag == 'B_TERM_DONE':
                _, bkey, tnode = stack.pop()
                if _result is None:
                    _memo[bkey] = None
                else:
                    _result = [tnode] + _result
                    _memo[bkey] = _result

            elif tag == 'B_NT_LOOP':
                _, bkey, body_, pos_, s_, e_, name_, mid_ = stack.pop()
                if mid_ > e_:
                    _result = None
                    _memo[bkey] = None
                else:
                    stack.append(('B_NT_AFTER_FIND', bkey, body_, pos_, s_, e_, name_, mid_))
                    stack.append(('F', name_, s_, mid_))

            elif tag == 'B_NT_AFTER_FIND':
                _, bkey, body_, pos_, s_, e_, name_, mid_ = stack.pop()
                node_ = _result
                if node_ is None:
                    stack.append(('B_NT_LOOP', bkey, body_, pos_, s_, e_, name_, mid_ + 1))
                else:
                    stack.append(('B_NT_AFTER_TAIL', bkey, body_, pos_, s_, e_, name_, mid_, node_))
                    stack.append(('B', body_, pos_ + 1, mid_, e_))

            elif tag == 'B_NT_AFTER_TAIL':
                _, bkey, body_, pos_, s_, e_, name_, mid_, node_ = stack.pop()
                tail_ = _result
                if tail_ is None:
                    stack.append(('B_NT_LOOP', bkey, body_, pos_, s_, e_, name_, mid_ + 1))
                else:
                    _result = [node_] + tail_
                    _memo[bkey] = _result

            elif tag == 'F':
                _, name_, s_, e_ = stack.pop()
                fkey = ('f', name_, s_, e_)
                if fkey in _memo:
                    _result = _memo[fkey]
                else:
                    items_ = completed.get((name_, s_, e_), [])
                    if not items_:
                        _result = None
                        _memo[fkey] = None
                    else:
                        stack.append(('F_NEXT', fkey, s_, e_, items_, 0))
                        stack.append(('R', items_[0], s_, e_))

            elif tag == 'F_NEXT':
                _, fkey, s_, e_, items_, idx_ = stack.pop()
                node_ = _result
                if node_ is not None:
                    _result = node_
                    _memo[fkey] = node_
                elif idx_ + 1 < len(items_):
                    stack.append(('F_NEXT', fkey, s_, e_, items_, idx_ + 1))
                    stack.append(('R', items_[idx_ + 1], s_, e_))
                else:
                    _result = None
                    _memo[fkey] = None

        return _result

    for rule_idx, dot, origin in chart[n]:
        head, body = _RULES[rule_idx]
        if head == _START and dot == len(body) and origin == 0:
            node = _recover(rule_idx, 0, n)
            if node is not None:
                return node
    raise ValueError('Parse failed')


def parse(tokens):
    return _parse_earley(list(tokens))

