#!/usr/bin/env python3
"""Compile the textual-DSL lexer and parsers to standalone modules.

Run after editing ``_dsl_grammar.py``::

    python tools/gen_text_dsl.py

Uses ``langforge`` (a local, editable, build-time-only tool) to emit
self-contained Python modules — with zero langforge/pydantic runtime
dependency — into ``src/aiogram_dialog_manager/spec/text/_generated/``. Those
generated handlers are what the package ships; the grammar configs never do.
"""
from __future__ import annotations

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
sys.path.insert(0, os.path.join(_HERE, "..", "src"))

from _dsl_grammar import EXPR_GRAMMAR, GRAMMAR, LEXER_CONFIG  # noqa: E402
from langforge.lexer import Lexer  # noqa: E402
from langforge.parser import Parser  # noqa: E402

_OUT = os.path.join(_HERE, "..", "src", "aiogram_dialog_manager", "spec", "text", "_generated")

_BANNER = (
    "# @generated by tools/gen_text_dsl.py from tools/_dsl_grammar.py — DO NOT EDIT.\n"
    "# Regenerate with: python tools/gen_text_dsl.py\n"
    "# ruff: noqa\n"
)


def _write(name: str, code: str) -> None:
    path = os.path.join(_OUT, name)
    with open(path, "w") as f:
        f.write(_BANNER + code)
    print(f"wrote {os.path.relpath(path)} ({code.count(chr(10))} lines)")


def main() -> None:
    os.makedirs(_OUT, exist_ok=True)
    lexer = Lexer(LEXER_CONFIG)
    file_parser = Parser({"grammar": "earley", "start": "file", "grammar_text": GRAMMAR})
    expr_parser = Parser({"grammar": "earley", "start": "expr", "grammar_text": EXPR_GRAMMAR})

    _write("__init__.py", '"""Generated DSL handlers (see tools/gen_text_dsl.py)."""\n')
    _write("lexer.py", lexer.generate_code())
    _write("parser_file.py", file_parser.generate_code())
    _write("parser_expr.py", expr_parser.generate_code())
    print("done")


if __name__ == "__main__":
    main()
