from .animation import AnimationMessagePrototype
from .audio import AudioMessagePrototype
from .contact import ContactMessagePrototype
from .document import DocumentMessagePrototype
from .location import LocationMessagePrototype
from .media_group import MediaGroupMessagePrototype
from .photo import PhotoMessagePrototype
from .poll import PollMessagePrototype
from .sticker import StickerMessagePrototype
from .text import TextMessagePrototype
from .video import VideoMessagePrototype
from .video_note import VideoNoteMessagePrototype
from .voice import VoiceMessagePrototype